//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administador.Model
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MESEntities : DbContext
    {
        public MESEntities()
            : base("name=MESEntities")
        {
        }

        public MESEntities(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Planta> Planta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
    }
}
